apiVersion: v1
kind: Service
metadata:
  name: hrboard-backend
  namespace: hrboard
spec:
  selector:
    app: hrboard-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrboard-backend
  namespace: hrboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrboard-backend
  template:
    metadata:
      labels:
        app: hrboard-backend
    spec:
      containers:
        - name: backend
          image: hrboard-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/hrboard